version: "3.8"

services:
  keycloak-postgres:
    image: postgres
    container_name: "${APP_NAME}-KeycloakPostgresDB"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_PG_DATABASE}
      POSTGRES_USER: ${KEYCLOAK_PG_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_PG_PASSWORD}

  keycloak-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: "${APP_NAME}-PGAdmin"
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${KEYCLOAK_PG_USERNAME}@keycloak-testing.com
      - PGADMIN_DEFAULT_PASSWORD=${KEYCLOAK_PG_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      - keycloak-postgres
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: "${APP_NAME}-Keycloak"
    volumes:
      - ./neofusion-keycloak-theme/build_keycloak/src/main/resources/theme/neofusion-keycloak-theme:/opt/keycloak/themes/neofusion-keycloak-theme
      - ./neofusion-keycloak-theme/build_keycloak/src/main/resources/theme/neofusion-keycloak-theme-1:/opt/keycloak/themes/keycloakify-poc-theme
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_PG_DATABASE}
      DB_USER: ${KEYCLOAK_PG_USERNAME}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_PG_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      - keycloak-postgres
    command: "start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false"

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  keycloak_data:
    driver: local
